<?php

namespace Database\Seeders;

use App\Models\JatahCuti;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'H. Palatanhar, SE., Ak',
                'gender' => 'Pria',
                'email' => 'h.palatanhar@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'direktur_operational',
            ],
            [
                'name' => 'Rosiana, SH., M.Hum',
                'gender' => 'Pria',
                'email' => 'rosiana@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_sdm',
            ],
            [
                'name' => 'Judi Iskandar, ST',
                'gender' => 'Pria',
                'email' => 'judi.iskandar@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Ahira Febrianti, SE',
                'gender' => 'Pria',
                'email' => 'ahira.febrianti@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Sydani Danu Putra, SH., M.M., M.H',
                'gender' => 'Pria',
                'email' => 'sydani.danu.putra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Ridwan Dwi Andi, SH',
                'gender' => 'Pria',
                'email' => 'ridwan.dwi.andi@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Cipta Rifky Maulana',
                'gender' => 'Pria',
                'email' => 'cipta.rifky.maulana@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Mukhlapa, SE',
                'gender' => 'Pria',
                'email' => 'mukhlapa@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Mns. Waisul Kurmi, ST',
                'gender' => 'Pria',
                'email' => 'mns.waisul.kurmi@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'M. Aidil Fikri, A.Md',
                'gender' => 'Pria',
                'email' => 'm.aidil.fikri@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Febryan Alfani',
                'gender' => 'Pria',
                'email' => 'febryan.alfani@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Aulia Rahmawati',
                'gender' => 'Pria',
                'email' => 'aulia.rahmawati@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Yeni Hidayati',
                'gender' => 'Pria',
                'email' => 'yeni.hidayati@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Nia Kartika Sari',
                'gender' => 'Pria',
                'email' => 'nia.kartika.sari@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Fikri Aditya',
                'gender' => 'Pria',
                'email' => 'fikri.aditya@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Dea Kartika',
                'gender' => 'Pria',
                'email' => 'dea.kartika@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Yoga Ari Pratama',
                'gender' => 'Pria',
                'email' => 'yoga.ari.pratama@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Andi Saputra',
                'gender' => 'Pria',
                'email' => 'andi.saputra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Nurul Rahmawati',
                'gender' => 'Pria',
                'email' => 'nurul.rahmawati@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Dian Permata Sari',
                'gender' => 'Pria',
                'email' => 'dian.permata.sari@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Riko Ardiansyah',
                'gender' => 'Pria',
                'email' => 'riko.ardiansyah@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Siti Aisyah',
                'gender' => 'Pria',
                'email' => 'siti.aisyah@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Agung Prasetyo',
                'gender' => 'Pria',
                'email' => 'agung.prasetyo@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Lina Marlina',
                'gender' => 'Pria',
                'email' => 'lina.marlina@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Indra Saputra',
                'gender' => 'Pria',
                'email' => 'indra.saputra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Desi Oktaviani',
                'gender' => 'Pria',
                'email' => 'desi.oktaviani@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Reza Mahendra',
                'gender' => 'Pria',
                'email' => 'reza.mahendra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Putri Amelia',
                'gender' => 'Pria',
                'email' => 'putri.amelia@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Budi Santoso',
                'gender' => 'Pria',
                'email' => 'budi.santoso@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Nadia Ayu Lestari',
                'gender' => 'Pria',
                'email' => 'nadia.ayu.lestari@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Rina Marlina',
                'gender' => 'Wanita',
                'email' => 'rina.marlina@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Dwi Handayani',
                'gender' => 'Wanita',
                'email' => 'dwi.handayani@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Hendra Saputra',
                'gender' => 'Pria',
                'email' => 'hendra.saputra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Yuliana Dewi',
                'gender' => 'Wanita',
                'email' => 'yuliana.dewi@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Rizky Ramadhan',
                'gender' => 'Pria',
                'email' => 'rizky.ramadhan@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Sulastri',
                'gender' => 'Wanita',
                'email' => 'sulastri@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Fauzan Hidayat',
                'gender' => 'Pria',
                'email' => 'fauzan.hidayat@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Nurlaila Hasanah',
                'gender' => 'Wanita',
                'email' => 'nurlaila.hasanah@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Rafi Ahmad',
                'gender' => 'Pria',
                'email' => 'rafi.ahmad@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
            [
                'name' => 'Tiara Lestari',
                'gender' => 'Wanita',
                'email' => 'tiara.lestari@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'karyawan',
            ],
        ];

        foreach ($users as $index => $user) {
            $user = User::create($user);

            JatahCuti::create([
                'users_id' => $user->id,
                'tahun' => now()->format('Y-01-01'),
                'total_jatah' => '20',
                'sisa_jatah' => '20'
            ]);
        }

        $atasan = [
            [
                'name' => 'Hardi Ferdiansah',
                'gender' => 'Pria',
                'email' => 'hardi.ferdiansyah@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_sdm',
            ],
            [
                'name' => 'Aan Ardianto',
                'gender' => 'Pria',
                'email' => 'aan.ardianto@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_sdm',
            ],
            [
                'name' => 'Muhammad Ilham',
                'gender' => 'Pria',
                'email' => 'muhammad.ilham@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_sdm',
            ],
            [
                'name' => 'M. Kokoh Pagestu',
                'gender' => 'Pria',
                'email' => 'mkokohpagestu@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Rinto Chandra',
                'gender' => 'Pria',
                'email' => 'rinto.chandra@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Bambang Hermanto',
                'gender' => 'Pria',
                'email' => 'bambang.hermanto@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'manajer_unit',
            ],
            [
                'name' => 'Dudi Iskandar',
                'gender' => 'Pria',
                'email' => 'dudi.iskandar@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'direktur_operational',
            ],
            [
                'name' => 'Efrilina',
                'gender' => 'Pria',
                'email' => 'efrilina@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'direktur_operational',
            ],
            [
                'name' => 'Dian Ariska Putri',
                'gender' => 'Pria',
                'email' => 'dian.ariska.putri@gmail.com',
                'password' => bcrypt('password'),
                'alamat' => '-',
                'no_telepon' => '-',
                'role' => 'direktur_operational',
            ],

        ];

        foreach ($atasan as $index => $user) {
            $user  = User::create($user);
        }
    }
}
